# Generated by Django 3.2.6 on 2024-09-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('label', models.ImageField(blank=True, upload_to='City/Images')),
                ('subtitle', models.CharField(max_length=256)),
                ('members', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
