# Generated by Django 3.2.6 on 2024-09-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccessIsKing', '0002_cityitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityItem',
        ),
    ]
