# Generated by Django 3.2.6 on 2024-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessIsKing', '0003_delete_cityitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='countryname',
            field=models.CharField(default=None, max_length=1024),
        ),
    ]
