# Generated by Django 3.2.6 on 2024-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessIsKing', '0004_city_countryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('comments', models.CharField(blank=True, max_length=1024)),
                ('media_files', models.ImageField(blank=True, upload_to='comment/Images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
